name: Build Windows Executable

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build executable in release mode
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: system_info_checker-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/system_info_checker.exe
